dataset:
  name_dataset: ChestXray
  ChestXray:
    train_path: ./chest_xray/train
    dev_path: ./chest_xray/val
    test_path: ./chest_xray/test
  Jewellery:
    train_path: ./Jewellery-Classification/dataset/training
    test_path: ./Jewellery-Classification/dataset/test
  Vegetable:
    train_path: ./Vegetable Images/train
    dev_path: ./Vegetable Images/validation
    test_path: ./Vegetable Images/test
train_batch: 128
dev_batch: 128
test_batch: 128
save_path: ./checkpoint
num_classes: 2
patience: 5
model: VGG16 # ResNet50, VGG19, VGG16
pretrained: True
freeze: True
learning_rate: 0.001
num_epochs: 5
seed: 52
best_metric: accuracy # accuracy, f1, precision, recall